import Config

# Configure your database
config :vulnerable_api, VulnerableApi.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "vulnerable_api_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :vulnerable_api, VulnerableApi.Guardian,
  issuer: "vulnerable_api",
  secret_key:
    System.get_env("GUARDIAN_SECRET_KEY") ||
      "JuGXNRQr7K5vHll02aYQRkUI+HXPWNMJsYLB1uyoMgzbaHV+l/AEGSecMHR0cu4F"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :vulnerable_api, VulnerableApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4200],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "CCTxI2BmMr37dmLLCXWuPjMx25S5POJ1P8WnTFkkSPMDDeL3zCpsFaTs3OjlP6Q4",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :vulnerable_api, VulnerableApi.Guardian,
  issuer: "vulnerable_api",
  secret_key:
    System.get_env("GUARDIAN_SECRET_KEY") ||
      "nEal75TIFR4JkHnANyrq3I681kutDXmtFmuedFQumrlrbQ2ZZE4ukqzBXTL7Y2c+"

# ttl: {1, :days}
